function apply_axes_style(ax,s)
% Explicit, renderer-independent axes defaults; callers set data limits.
set(ax,'FontName',s.FontName,'FontSize',s.AxisFontSize,...
    'LineWidth',s.AxisLineWidth,'Color','white','Box','off',...
    'TickDir','out','TickLabelInterpreter','tex',...
    'XGrid','off','YGrid','on','GridColor',[.7 .7 .7],...
    'GridAlpha',.35,'GridLineStyle','-','Layer','top');
ax.XLabel.FontSize = s.LabelFontSize;
ax.YLabel.FontSize = s.LabelFontSize;
ax.Title.FontSize = s.TitleFontSize;
ax.Title.FontWeight = 'normal';
end
