function catalog = stackelberg_irf_catalog()
% Single source of truth for the first-round Scheme-B IRF export.

catalog.shock = "emp";
catalog.shock_suffix = '_emp';
catalog.horizon = 40;
catalog.variable = ["mp"; "r"; "pinfagg"; ...
    "pinf1"; "pinf2"; "rb1"; "rb2"; "dann1"; "dann2"; ...
    "ds1"; "ds2"; "fs1"; "fs2"; "lamg1"; "lamg2"; ...
    "qg1"; "qg2"; "ig1"; "ig2"; "kg1"; "kg2"; ...
    "xloc1"; "xloc2"; "k1"; "k2"; "inv1"; "inv2"; ...
    "qk1"; "qk2"; "n1"; "n2"; "w1"; "w2"; "rk1"; "rk2"; ...
    "muR_1"; "muK_1"; "muQ_1"; "muI_1"; ...
    "muR_2"; "muK_2"; "muQ_2"; "muI_2"];
catalog.region = ["national"; "national"; "national"; ...
    repmat(["low_debt"; "high_debt"], 16, 1); ...
    repmat("low_debt", 4, 1); repmat("high_debt", 4, 1)];

catalog.gap_low = ["pinf1"; "rb1"; "dann1"; "ds1"; "fs1"; ...
    "lamg1"; "qg1"; "ig1"; "kg1"; "xloc1"; "k1"; "inv1"; ...
    "qk1"; "n1"; "w1"; "rk1"; "muR_1"; ...
    "muK_1"; "muQ_1"; "muI_1"];
catalog.gap_high = ["pinf2"; "rb2"; "dann2"; "ds2"; "fs2"; ...
    "lamg2"; "qg2"; "ig2"; "kg2"; "xloc2"; "k2"; "inv2"; ...
    "qk2"; "n2"; "w2"; "rk2"; "muR_2"; ...
    "muK_2"; "muQ_2"; "muI_2"];
catalog.gap_name = ["pinf_gap_2_minus_1"; "rb_gap_2_minus_1"; ...
    "dann_gap_2_minus_1"; "ds_gap_2_minus_1"; ...
    "fs_gap_2_minus_1"; "lamg_gap_2_minus_1"; ...
    "qg_gap_2_minus_1"; "ig_gap_2_minus_1"; ...
    "kg_gap_2_minus_1"; "xloc_gap_2_minus_1"; ...
    "k_gap_2_minus_1"; "inv_gap_2_minus_1"; ...
    "qk_gap_2_minus_1"; "n_gap_2_minus_1"; ...
    "w_gap_2_minus_1"; "rk_gap_2_minus_1"; ...
    "muR_gap_2_minus_1"; ...
    "muK_gap_2_minus_1"; ...
    "muQ_gap_2_minus_1"; "muI_gap_2_minus_1"];

if numel(catalog.variable) ~= numel(catalog.region)
    error('IRF variable and region maps have different lengths.');
end
if numel(catalog.gap_low) ~= numel(catalog.gap_high) ...
        || numel(catalog.gap_low) ~= numel(catalog.gap_name)
    error('IRF gap maps have different lengths.');
end
end
